apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      plex:
        strategy: Recreate
        containers:
          app:
            image:
              repository: linuxserver/plex
              tag: latest
              pullPolicy: IfNotPresent
            env:
              PUID: "1000"
              PGID: "1000"
              TZ: "UTC"
              VERSION: "docker"
              # PLEX_CLAIM: "claim-XXXXXXXXXXXXXXXXXXXX"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 32400
                  initialDelaySeconds: 30
                  periodSeconds: 10
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 32400
                  initialDelaySeconds: 15
                  periodSeconds: 10
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                cpu: "2"
                memory: 2Gi
    service:
      app:
        controller: plex
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "192.168.2.245"
        ports:
          http:
            port: 32400
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 50Gi
        storageClass: nfs-appdata
        globalMounts:
          - path: /config
      data:
        type: persistentVolumeClaim
        existingClaim: media-data
        globalMounts:
          - path: /data
      transcode:
        type: emptyDir
        globalMounts:
          - path: /transcode
