# Shared media volume — mounted by Plex, Sonarr, Radarr, qBittorrent, Bazarr.
# All apps see the same filesystem so Sonarr/Radarr can hardlink completed
# downloads into the media library (no duplicate copies).
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-data-pv
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: media-data-pv
    volumeAttributes:
      server: "192.168.2.129"
      share: "/volume1/nfs01/data"
  mountOptions:
    - nfsvers=3
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Ti
  volumeName: media-data-pv
