apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      tautulli:
        strategy: Recreate
        containers:
          app:
            image:
              repository: linuxserver/tautulli
              tag: latest
              pullPolicy: IfNotPresent
            env:
              PUID: "1000"
              PGID: "1000"
              TZ: "UTC"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: 8181
                  periodSeconds: 10
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: 8181
                  periodSeconds: 10
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 250m
                memory: 256Mi
    service:
      app:
        controller: tautulli
        ports:
          http:
            port: 8181
    ingress:
      app:
        className: traefik
        hosts:
          - host: tautulli.media.lan
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: nfs-appdata
        globalMounts:
          - path: /config
