apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: 0.28.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    # Dev mode for homelab - auto-unseals, non-HA, in-memory storage
    # For production, use HA mode with raft storage and manual unsealing
    server:
      dev:
        enabled: true
        devRootToken: "root" # Change this to a secure token

      # Enable standalone mode (single replica for dev)
      standalone:
        enabled: true

      # Resource limits for homelab
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 512Mi
          cpu: 500m

      # Service configuration
      service:
        enabled: true
        type: ClusterIP
        port: 8200

      # Enable UI
      ui:
        enabled: true

      # Ingress disabled - access via kubectl port-forward or create separate ingress
      ingress:
        enabled: false

      # Data storage - use emptyDir for dev mode
      dataStorage:
        enabled: false

      # Audit storage
      auditStorage:
        enabled: false

    # Injector for automatic secret injection (optional)
    injector:
      enabled: true
      resources:
        requests:
          memory: 64Mi
          cpu: 50m
        limits:
          memory: 128Mi
          cpu: 100m

    # UI service
    ui:
      enabled: true
