# YAML anchors for common Vault configuration
# These anchors prevent duplication across multiple SecretStore resources
---
# ClusterSecretStore for vault - accessible from all namespaces
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  # Provider configuration - Vault
  provider:
    vault:
      server: &vaultServer "http://vault.vault.svc.cluster.local:8200"
      path: &vaultPath "secret"
      version: &vaultVersion "v2"
      auth:
        # Using Kubernetes auth method
        kubernetes:
          mountPath: &vaultAuthMount "kubernetes"
          role: &vaultRole "external-secrets"
          serviceAccountRef:
            name: external-secrets
---
# SecretStore for media namespace
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: media
spec:
  provider:
    vault:
      server: *vaultServer
      path: *vaultPath
      version: *vaultVersion
      auth:
        kubernetes:
          mountPath: *vaultAuthMount
          role: *vaultRole
          serviceAccountRef:
            name: external-secrets-sa
            namespace: media
---
# SecretStore for monitoring namespace (if you create one)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: monitoring
spec:
  provider:
    vault:
      server: *vaultServer
      path: *vaultPath
      version: *vaultVersion
      auth:
        kubernetes:
          mountPath: *vaultAuthMount
          role: *vaultRole
          serviceAccountRef:
            name: external-secrets-sa
            namespace: monitoring
