# YAML anchors for common ExternalSecret configuration
# This prevents duplication and makes maintenance easier
---
# Anchor definitions for reuse
x-common-config: &commonConfig
  refreshInterval: 15m
  target:
    creationPolicy: Owner
    deletionPolicy: Retain

x-vault-store: &vaultStore
  name: vault-backend
  kind: SecretStore

# Gmail SMTP credentials for Grafana alerting
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gmail-smtp-secret
  namespace: monitoring
spec:
  <<: *commonConfig
  secretStoreRef:
    <<: *vaultStore
  target:
    name: gmail-smtp-secret
    template:
      engineVersion: v2
      data:
        # Template for Grafana SMTP configuration
        smtp_host: smtp.gmail.com:587
        smtp_user: "{{ .email }}"
        smtp_password: "{{ .password }}"
  dataFrom:
  - extract:
      key: monitoring/gmail-smtp
---
# Pushbullet API token for Grafana notifications
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pushbullet-secret
  namespace: monitoring
spec:
  <<: *commonConfig
  secretStoreRef:
    <<: *vaultStore
  target:
    name: pushbullet-secret
    template:
      engineVersion: v2
      data:
        # Format for Grafana contact point
        pushbullet_token: "{{ .token }}"
        authorization_credentials: "{{ .token }}"
  dataFrom:
  - extract:
      key: monitoring/pushbullet
---
# Grafana admin credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  <<: *commonConfig
  secretStoreRef:
    <<: *vaultStore
  target:
    name: grafana-admin-secret
    template:
      engineVersion: v2
      data:
        admin-user: "{{ .username }}"
        admin-password: "{{ .password }}"
  dataFrom:
  - extract:
      key: monitoring/grafana-admin
